# Generated by Django 2.1.5 on 2019-04-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News in english'},
        ),
    ]
