# Generated by Django 2.1.5 on 2019-01-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
