# Generated by Django 2.0.3 on 2018-10-04 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Lokasi', models.TextField()),
                ('Mulai', models.DateTimeField()),
                ('Akhir', models.DateTimeField()),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Img', models.FileField(blank=True, null=True, upload_to='acara/')),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='istana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('Gambar', models.FileField(null=True, upload_to='istana/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='karya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Index', models.CharField(max_length=50)),
                ('Judul', models.CharField(max_length=50)),
                ('Jenis', models.CharField(choices=[('Lukisan', 'Lukisan'), ('Patung', 'Patung'), ('Kriya', 'Kriya')], max_length=10)),
                ('Dimensi', models.CharField(max_length=25)),
                ('Material', models.CharField(max_length=20)),
                ('Tahun_Pembuatan', models.DateField(blank=True, null=True)),
                ('Gambar', models.FileField(upload_to='karya/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
                ('Lokasi_Lukisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singgasanaseni.istana')),
            ],
        ),
        migrations.CreateModel(
            name='kurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('Tempat_Lahir', models.CharField(max_length=50)),
                ('Tanggal_Lahir', models.DateField(blank=True, null=True)),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Gambar', models.FileField(blank=True, null=True, upload_to='kurator/')),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='perupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Panggilan', models.CharField(blank=True, max_length=20, null=True)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('Tempat_Lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('Tanggal_Lahir', models.DateField()),
                ('Tempat_Wafat', models.CharField(blank=True, max_length=50, null=True)),
                ('Tanggal_Wafat', models.DateField(blank=True, null=True)),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Gambar', models.FileField(blank=True, null=True, upload_to='perupa/')),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='karya',
            name='Perupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singgasanaseni.perupa'),
        ),
    ]
