# Generated by Django 2.1.5 on 2019-02-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perupa',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
