# Generated by Django 2.1.5 on 2019-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='homeslide',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='karya',
            options={'verbose_name_plural': 'Karya'},
        ),
        migrations.AlterModelOptions(
            name='perupa',
            options={'verbose_name_plural': 'Perupa'},
        ),
        migrations.AddField(
            model_name='perupa',
            name='Link',
            field=models.TextField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='perupa',
            name='Sumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
