# Generated by Django 2.0.3 on 2018-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perupa',
            name='Tanggal_Lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
