# Generated by Django 2.2 on 2019-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Judul', models.CharField(max_length=50)),
                ('Pertanyaan', models.TextField()),
                ('Replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Inquiry',
            },
        ),
    ]
