# Generated by Django 2.0.3 on 2018-10-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0002_auto_20181004_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='Perupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyalist', to='singgasanaseni.perupa'),
        ),
    ]
