# Generated by Django 2.2 on 2019-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0002_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='Judul_EN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='karya',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
