# Generated by Django 2.0.3 on 2018-10-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0003_auto_20181024_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='Perupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singgasanaseni.perupa'),
        ),
    ]
