# Generated by Django 2.0.3 on 2018-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0004_auto_20181024_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='Kategori',
            field=models.CharField(choices=[('Potret', 'Potret dan Sensualitas'), ('Alam', 'Alam dan Benda'), ('Pemandangan', 'Pemandangan Alam dan Kota'), ('Perjuangan', 'Perjuangan dan Potret Para Pejuang'), ('Tradisi', 'Tradisi/Budaya/Mitologi/Keseharian'), ('Patung', 'Patung dan Kriya')], default=True, max_length=25),
        ),
    ]
