# Generated by Django 2.0.3 on 2018-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0005_karya_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Judul', models.TextField()),
                ('Subjudul', models.TextField(blank=True, null=True)),
                ('Sumber', models.CharField(max_length=10)),
                ('Link', models.TextField()),
                ('Isiberita', models.TextField()),
                ('Gambar', models.FileField(blank=True, upload_to='berita/')),
                ('Published', models.BooleanField(default=True)),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='acara',
        ),
        migrations.DeleteModel(
            name='kurator',
        ),
        migrations.AddField(
            model_name='perupa',
            name='Kategori',
            field=models.CharField(choices=[('Pelukis', 'Pelukis'), ('Pematung', 'Pematung'), ('Pengrajin', 'Pengrajin')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='karya',
            name='Kategori',
            field=models.CharField(choices=[('Potret dan Sensualitas', 'Potret dan Sensualitas'), ('Alam dan Benda', 'Alam dan Benda'), ('Pemandangan Alam dan Kota', 'Pemandangan Alam dan Kota'), ('Perjuangan dan Potret Para Pejuang', 'Perjuangan dan Potret Para Pejuang'), ('Tradisi/Budaya/Mitologi/Keseharian', 'Tradisi/Budaya/Mitologi/Keseharian'), ('Patung dan Kriya', 'Patung dan Kriya')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='karya',
            name='No_Index',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
