# Generated by Django 2.0.3 on 2018-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0006_auto_20181114_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='Lokasi_Lukisan',
            field=models.CharField(choices=[('Istana Bogor', 'Istana Bogor'), ('Istana Tampak Siring', 'Istana Tampak Siring')], default=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='istana',
        ),
    ]
