# Generated by Django 2.1.2 on 2018-11-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0007_auto_20181115_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perupa',
            name='Panggilan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
