# Generated by Django 2.1.2 on 2018-12-18 10:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0008_auto_20181128_1247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='berita',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='karya',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='perupa',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='karya',
            name='Adult_Material',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='karya',
            name='Lokasi_Lukisan',
            field=models.CharField(choices=[('Istana Bogor', 'Istana Bogor'), ('Istana Tampak Siring', 'Istana Tampak Siring'), ('Istana Merdeka', 'Istana Merdeka'), ('Istana Negara', 'Istana Negara'), ('Istana Cipanas', 'Istana Cipanas'), ('istana Yogya', 'Istana Yogya')], default=True, max_length=20),
        ),
    ]
