# Generated by Django 2.1.2 on 2018-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0009_auto_20181218_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='Judul',
            field=models.CharField(max_length=100),
        ),
    ]
