# Generated by Django 2.1.2 on 2018-12-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singgasanaseni', '0010_auto_20181218_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karya',
            old_name='Adult_Material',
            new_name='Naked_Material',
        ),
    ]
