# Generated by Django 2.1.2 on 2019-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.FileField(upload_to='homepage/')),
                ('caption1', models.CharField(blank=True, max_length=25, null=True)),
                ('subcaption1', models.CharField(blank=True, max_length=50, null=True)),
                ('slide2', models.FileField(upload_to='homepage/')),
                ('caption2', models.CharField(blank=True, max_length=25, null=True)),
                ('subcaption2', models.CharField(blank=True, max_length=50, null=True)),
                ('slide3', models.FileField(upload_to='homepage/')),
                ('caption3', models.CharField(blank=True, max_length=25, null=True)),
                ('subcaption3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
