# Generated by Django 2.1.5 on 2019-01-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='link1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='link2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='link3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
